#!/usr/bin/env python3
"""
Plot a phonon band structure (dispersion along high-symmetry lines) from a
completed AiiDA PhonopyFleurWorkChain, using its force constants directly.

The high-symmetry path is auto-generated by seekpath from the primitive
cell (same approach as analyse_phonons() in run_phonopy_manual.py).

Usage:
    verdi -p presto_pg run scripts/phonon/by_aiida/plot_aiida_band_structure.py \
        --pk 93126 --npoints 51 \
        --output summary/phonon_thermo/ZnO_186_band_structure.png
"""

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from phonopy import Phonopy
from phonopy.structure.atoms import PhonopyAtoms
from phonopy.units import VaspToCm

IMAG_THRESHOLD_CM1 = -1.67


def get_seekpath_bands(ph, npoints: int):
    """Build a high-symmetry q-point path via seekpath from the primitive cell.

    seekpath.get_path() needs the full (cell, positions, numbers) tuple, not
    just the lattice -- passing ph.primitive.cell alone (as
    analyse_phonons() in run_phonopy_manual.py does) is a TypeError/wrong
    result, not a valid call.
    """
    import seekpath

    prim = ph.primitive
    structure = (prim.cell, prim.scaled_positions, prim.numbers)
    path_info = seekpath.get_path(structure)

    pts = []
    labels = []
    for seg in path_info["path"]:
        for name in seg:
            coord = path_info["point_coords"][name]
            if not pts or np.linalg.norm(np.array(coord) - np.array(pts[-1])) > 1e-9:
                pts.append(coord)
                labels.append(name)

    band_paths = []
    for i in range(len(pts) - 1):
        start, end = np.array(pts[i]), np.array(pts[i + 1])
        band_paths.append(
            [start + (end - start) * t for t in np.linspace(0, 1, npoints)]
        )
    return band_paths, labels


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pk", type=int, required=True)
    ap.add_argument("--npoints", type=int, default=51, help="points per segment")
    ap.add_argument("--label", default=None)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()

    from aiida.orm import load_node

    wc = load_node(args.pk)
    structure = wc.inputs.structure
    supercell_matrix = np.array(wc.inputs.supercell_matrix.get_list())
    fc = wc.outputs.output_phonopy.output_force_constants.get_array(
        "force_constants"
    )

    ase_atoms = structure.get_ase()
    unitcell = PhonopyAtoms(
        symbols=ase_atoms.get_chemical_symbols(),
        cell=ase_atoms.get_cell(),
        scaled_positions=ase_atoms.get_scaled_positions(),
    )

    ph = Phonopy(unitcell, supercell_matrix=supercell_matrix, factor=VaspToCm)
    ph.force_constants = fc
    ph.symmetrize_force_constants()

    band_paths, labels = get_seekpath_bands(ph, args.npoints)
    ph.run_band_structure(band_paths, with_eigenvectors=False)
    band_dict = ph.get_band_structure_dict()
    frequencies = band_dict["frequencies"]
    distances = band_dict["distances"]

    fig, ax = plt.subplots(figsize=(9, 5.5))
    x_offset = 0.0
    tick_positions = [0.0]
    for i, (freqs_seg, dist_seg) in enumerate(zip(frequencies, distances)):
        x = np.array(dist_seg) - dist_seg[0] + x_offset
        for band in range(freqs_seg.shape[1]):
            ax.plot(x, freqs_seg[:, band], color="b", linewidth=1.0)
        x_offset = x[-1]
        tick_positions.append(x_offset)
        if i < len(band_paths) - 1:
            ax.axvline(x_offset, color="gray", linewidth=0.5)

    ax.axhline(0, color="k", linewidth=0.6, linestyle="--")
    ax.set_xticks(tick_positions)
    ax.set_xticklabels([f"${l}$" if l != "GAMMA" else "$\\Gamma$" for l in labels])
    ax.set_xlim(0, tick_positions[-1])
    ax.set_ylabel("Frequency [cm$^{-1}$]")
    title = args.label or f"Phonon dispersion, PhonopyFleurWorkChain<{args.pk}>"
    ax.set_title(title)
    ax.grid(True, alpha=0.2)

    plt.tight_layout()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(args.output, dpi=150)
    print(f"saved {args.output}")

    n_imag = sum(int(np.sum(freqs_seg < IMAG_THRESHOLD_CM1)) for freqs_seg in frequencies)
    print(f"imaginary modes along path (< {IMAG_THRESHOLD_CM1} cm^-1): {n_imag}")


if __name__ == "__main__":
    main()
